/**
 * Gaia's lexicon — ported from Gaia Web so both clients speak with one
 * voice. Dutch is the default. Only the strings the desktop uses.
 */
export const LANGUAGES = {
  nl: {
    newPage: 'Nieuw gesprek',
    untitled: 'Naamloos gesprek',
    composerPlaceholder: 'Zeg wat je wilt, of denk hardop…',
    healthWhisper:
      'Ik kan mijn denkmotor momenteel niet bereiken. Neem je tijd — ik ben er als je klaar bent om het opnieuw te proberen.',
    retry: 'Opnieuw proberen',
    footLine1: 'Een levenslange persoonlijke intelligentie,',
    footLine2: 'die groeit door begrip.',
    settings: 'Instellingen',
    settingsTitle: 'Instellingen',
    settingsCloud: 'Gaia Cloud',
    settingsServerUrl: 'Server-URL',
    settingsAuthToken: 'Authenticatietoken',
    settingsTest: 'Verbinding testen',
    settingsTesting: 'Testen…',
    settingsBehaviour: 'Gedrag',
    settingsNotifications: 'Notificaties',
    settingsQuiet: 'Stille aanwezigheid (niet storen)',
    settingsVolume: 'Spraakvolume',
    settingsMuted: 'Spraak dempen',
    settingsCapabilities: 'Lokale mogelijkheden',
    settingsMicrophone: 'Microfoon',
    settingsCaptureSources: 'Capturebronnen',
    settingsCaptureNone: 'nog geen geregistreerd',
    settingsMcp: 'MCP-toolservers',
    settingsMcpHint: 'Lokale tool­servers (MCP, stdio) die Gaia technisch kan aanroepen. Wat een tool betekent, beslist Gaia Cloud — de desktop biedt alleen de uitvoering.',
    settingsMcpEmpty: 'Nog geen toolservers geconfigureerd.',
    settingsMcpAdd: 'Toolserver toevoegen',
    settingsMcpRemove: 'Verwijderen',
    settingsMcpCommand: 'Startopdracht',
    settingsMcpArgs: 'Argumenten (spatie-gescheiden)',
    settingsMcpTools: 'Tools tonen',
    settingsMcpToolsLoading: 'Laden…',
    settingsMcpToolsFailed: 'Tools konden niet worden opgehaald.',
    settingsSave: 'Bewaren',
    settingsSaving: 'Behouden…',
    settingsSaved: 'Bewaard',
    settingsClose: 'Sluiten',
    deleteConversation: 'Gesprek verwijderen',
    send: 'Versturen',
    library: 'Bibliotheek',
    libraryTitle: 'Bibliotheek',
    libraryHint: 'Bestanden die je aan Gaia geeft, bewaard in Gaia Cloud — niet alleen op dit apparaat.',
    libraryUpload: 'Bestand toevoegen',
    libraryUploading: 'Toevoegen…',
    libraryUploadFailed: 'Toevoegen is niet gelukt. Probeer het opnieuw.',
    libraryDownload: 'Downloaden',
    libraryDownloadFailed: 'Downloaden is niet gelukt.',
    libraryDelete: 'Verwijderen',
    libraryDeleteFailed: 'Verwijderen is niet gelukt.',
    libraryEmpty: 'Nog geen bestanden.',
    composerAttach: 'Bestand toevoegen als context',
    history: 'Geschiedenis',
    historyTitle: 'Geschiedenis',
    historyHint: 'Gesprekken die Gaia Cloud heeft bewaard, over al je sessies heen — niet alleen deze.',
    historyEmpty: 'Nog geen bewaarde gesprekken.',
    historyMessages: 'berichten',
    historyOpenFailed: 'Dit gesprek kon niet worden geopend.',
    historyDelete: 'Verwijderen',
    historyDeleteFailed: 'Verwijderen is niet gelukt.',
    historyExport: 'Exporteren',
    historyExportFailed: 'Exporteren is niet gelukt.',
    // cognition review (human Absolute Override)
    cognition: 'Begrip',
    cognitionTitle: 'Wat ik begrijp',
    cognitionHint: 'Wat ik meen op te merken, wacht op jouw oordeel. Jij bevestigt — ik niet.',
    cognitionEmpty: 'Er wacht nu niets op je oordeel.',
    cognitionLoading: 'Laden…',
    cognitionLoadFailed: 'Dit kon ik niet ophalen.',
    cognitionOpenFailed: 'Dit kon ik niet openen.',
    cognitionConfirm: 'Bevestigen',
    cognitionReject: 'Loslaten',
    cognitionTesting: 'Onderzoeken',
    cognitionConfirmed: 'Bevestigd',
    cognitionRejected: 'Losgelaten',
    cognitionInteresting: 'Onderzoek dit',
    cognitionReason: 'Reden (optioneel)',
    cognitionActionFailed: 'Dit is niet gelukt. Probeer het opnieuw.',
    cognitionStatusProposed: 'voorgesteld',
    cognitionStatusTesting: 'in onderzoek',
    cognitionStatusCorroborated: 'bevestigd door herhaling',
    cognitionStatusConfirmed: 'bevestigd',
    cognitionStatusRejected: 'losgelaten',
    cognitionScopeMicro: 'micro',
    cognitionScopeMacro: 'wezenlijk',
    cognitionCounterHypothesis: 'Tegenhypothese',
    cognitionCounterHint: 'De tegenwerping die ik tegenhield — geen feit, alleen voor jouw oordeel.',
    cognitionShowCounter: 'Bekijk de tegenhypothese',
    cognitionHideCounter: 'Verberg de tegenhypothese',
    cognitionCounterMissing: 'Nog geen tegenhypothese — bevestigen kan pas zodra die er is.',
    cognitionEvidence: 'Bewijs',
    cognitionEvidenceFor: 'voor',
    cognitionEvidenceAgainst: 'tegen',
    cognitionNoEvidence: 'Nog geen bewijs gekoppeld.',
    cognitionMacroNote: 'Dit raakt iets wezenlijks. Bevestigen vraagt een bewuste afweging.',
    cognitionImplicationPrompt: 'Wat betekent bevestigen hier?',
    cognitionImplicationEstablish: 'Ik stel deze stelling vast, zoals hierboven.',
    cognitionImplicationCounter: 'Ik stel de tegenhypothese vast.',
    cognitionImplicationSoft: 'Ik geef alleen het vertrouwen een zetje.',
    cognitionImplicationPickCorrect: 'Kies eerst wat vaststellen hier betekent.',
    cognitionNuance: 'Nuanceren',
    cognitionNuanceHint: 'Herschrijf de stelling zoals jij het bedoelt (optioneel).',
    cognitionNuancePlaceholder: 'Jouw formulering…',
    cognitionReopen: 'Heroverwegen',
    cognitionReopenHint: 'Je hebt dit losgelaten. Wil je het toch weer in onderzoek nemen? Zeg waarom.',
    cognitionReopenPlaceholder: 'Waarom heroverwegen?',
    cognitionReopenRequired: 'Een reden is verplicht om te heroverwegen.',
    cognitionRailOpen: 'Begrip openen',
    cognitionRailNew: 'Nieuwe dingen in Begrip',
    cognitionClose: 'Sluiten',
    cognitionResize: 'Formaat aanpassen',
    cognitionAsk: 'Klopt dit?',
    cognitionYes: 'Ja',
    cognitionNo: 'Nee',
    cognitionMore: 'Meer',
    cognitionLess: 'Minder',
    cognitionBack: 'Terug',
    cognitionMacroSure: 'Weet je het zeker? Je stelt dit vast als iets wezenlijks.',
    // Logos — episodes (interpretation first, observations on request)
    logos: 'Logos',
    logosTitle: 'Tijdlijn',
    logosHint:
      'Episodes die Logos in je activiteit herkende. Wat je leest is een interpretatie — het bewijs zit eronder, op verzoek.',
    logosEmpty: 'Logos heeft nog geen episode herkend.',
    logosLoading: 'Episodes laden…',
    logosLoadFailed: 'Logos kon de episodes niet ophalen.',
    logosClose: 'Sluiten',
    logosEpisodeBadge: 'Episode / Interpretatie',
    logosBadgeHint: 'Logos leidde dit af uit de observaties hieronder — het is geen letterlijk feit.',
    logosSessionPrefix: 'Sessie',
    logosConfidence: 'zekerheid',
    logosContext: 'Betrokken context',
    logosEvidenceToggle: 'Bekijk ruwe bewijslast',
    logosCaptures: 'captures',
    logosCapture: 'capture',
    logosEvidenceEmpty: 'Geen ruwe observaties gevonden.',
    logosEvidenceFailed: 'De ruwe bewijslast kon niet worden opgehaald.',
    logosRawObservations: 'Ruwe observaties',
    logosRawNote: 'Rechtstreeks vastgelegd door capture-rs — niet door Logos geschreven.',
    logosOcr: 'OCR',
    logosUia: 'UIA',
    logosAskGaia: 'Vraag Gaia',
    logosAskGaiaNotice: 'Gaia opent een gesprek met deze episode als context.',
    // turn failure phrases (phrases.js reads these)
    turnNoServer: 'Gaia is nog niet verbonden met haar server. Je kunt er een toevoegen in de instellingen.',
    turnUnreachable: 'Gaia is nu even niet te bereiken.',
    turnUnauthorized: 'Gaia weigert deze verbinding. Controleer het token in de instellingen.',
    turnCapture: 'Dit apparaat kon dat niet vastleggen.',
    turnFallback: 'Er ging hier iets mis. Je bericht staat er nog.',
    connectionTitle: 'Geen verbinding',
    connectionMessage: 'Gaia kan haar server niet bereiken. Controleer je gegevens in de instellingen.',
    connectionOpenSettings: 'Instellingen openen',
    connectionDismiss: 'Sluiten',
    thoughtProcess: 'Gedachtegang',
    aboutTitle: 'Over Gaia',
    aboutCloud: 'Cloud',
    aboutDesktop: 'Desktop',
    aboutBuild: 'build',
    aboutVersion: 'Versie',
    aboutUnavailable: 'niet beschikbaar',
    aboutConnected: 'verbonden',
    aboutClose: 'Sluiten',
    // Update panel
    updateTitle: 'Updates',
    updateHint: 'Controleren op updates...',
    updateChecking: 'Controleren op updates...',
    updateAvailable: 'Update beschikbaar',
    updateDescription: 'Een nieuwe versie is klaar om te installeren.',
    updateVersion: 'Versie',
    updateInstall: 'Update installeren',
    updateInstalling: 'Update aan het installeren...',
    updateDownloaded: 'Update succesvol gedownload!',
    updateRestartHint: 'De applicatie moet herstarten om de update te voltooien.',
    updateRestart: 'Nu herstarten',
    updateNotAvailable: 'Je hebt de nieuwste versie.',
    updateCheckAgain: 'Nogmaals controleren',
    updateError: 'Update controle mislukt',
    updateRetry: 'Opnieuw proberen',
    updateSettings: 'Updates',
    updateCheckForUpdates: 'Controleren op updates',
  },
  en: {
    newPage: 'New conversation',
    untitled: 'Untitled conversation',
    composerPlaceholder: 'Say anything, or just think out loud…',
    healthWhisper: "I can't reach my reason engine right now. Take your time — I'm here when you're ready to try again.",
    retry: 'Retry',
    footLine1: 'A lifelong personal intelligence,',
    footLine2: 'growing through understanding.',
    settings: 'Settings',
    settingsTitle: 'Settings',
    settingsCloud: 'Gaia Cloud',
    settingsServerUrl: 'Server URL',
    settingsAuthToken: 'Auth token',
    settingsTest: 'Test connection',
    settingsTesting: 'Testing…',
    settingsBehaviour: 'Behaviour',
    settingsNotifications: 'Notifications',
    settingsQuiet: 'Quiet presence (do not disturb)',
    settingsVolume: 'Voice volume',
    settingsMuted: 'Mute voice',
    settingsCapabilities: 'Local capabilities',
    settingsMicrophone: 'Microphone',
    settingsCaptureSources: 'Capture sources',
    settingsCaptureNone: 'none registered yet',
    settingsMcp: 'MCP tool servers',
    settingsMcpHint: 'Local tool servers (MCP, stdio) Gaia can technically invoke. What a tool means is decided by Gaia Cloud — the desktop only provides execution.',
    settingsMcpEmpty: 'No tool servers configured yet.',
    settingsMcpAdd: 'Add tool server',
    settingsMcpRemove: 'Remove',
    settingsMcpCommand: 'Launch command',
    settingsMcpArgs: 'Arguments (space-separated)',
    settingsMcpTools: 'Show tools',
    settingsMcpToolsLoading: 'Loading…',
    settingsMcpToolsFailed: 'Could not fetch tools.',
    settingsSave: 'Save',
    settingsSaving: 'Saving…',
    settingsSaved: 'Saved',
    settingsClose: 'Close',
    deleteConversation: 'Delete conversation',
    send: 'Send',
    library: 'Library',
    libraryTitle: 'Library',
    libraryHint: 'Files you give Gaia, stored in Gaia Cloud — not just on this device.',
    libraryUpload: 'Add file',
    libraryUploading: 'Adding…',
    libraryUploadFailed: 'Could not add the file. Please try again.',
    libraryDownload: 'Download',
    libraryDownloadFailed: 'Could not download the file.',
    libraryDelete: 'Delete',
    libraryDeleteFailed: 'Could not delete the file.',
    libraryEmpty: 'No files yet.',
    composerAttach: 'Attach a file as context',
    history: 'History',
    historyTitle: 'History',
    historyHint: 'Conversations Gaia Cloud has saved, across every past session — not just this one.',
    historyEmpty: 'No saved conversations yet.',
    historyMessages: 'messages',
    historyOpenFailed: 'Could not open this conversation.',
    historyDelete: 'Delete',
    historyDeleteFailed: 'Could not delete this conversation.',
    historyExport: 'Export',
    historyExportFailed: 'Could not export this conversation.',
    // cognition review (human Absolute Override)
    cognition: 'Understanding',
    cognitionTitle: 'What I understand',
    cognitionHint: 'What I think I notice, waiting for your judgement. You confirm — I do not.',
    cognitionEmpty: 'Nothing is awaiting your judgement right now.',
    cognitionLoading: 'Loading…',
    cognitionLoadFailed: 'Could not fetch this.',
    cognitionOpenFailed: 'Could not open this.',
    cognitionConfirm: 'Confirm',
    cognitionReject: 'Let go',
    cognitionTesting: 'Examine',
    cognitionConfirmed: 'Confirmed',
    cognitionRejected: 'Let go',
    cognitionInteresting: 'Look into this',
    cognitionReason: 'Reason (optional)',
    cognitionActionFailed: 'That did not work. Please try again.',
    cognitionStatusProposed: 'proposed',
    cognitionStatusTesting: 'under examination',
    cognitionStatusCorroborated: 'corroborated',
    cognitionStatusConfirmed: 'confirmed',
    cognitionStatusRejected: 'let go',
    cognitionScopeMicro: 'micro',
    cognitionScopeMacro: 'high-impact',
    cognitionCounterHypothesis: 'Counter-hypothesis',
    cognitionCounterHint: 'The objection I held back — not a fact, only for your judgement.',
    cognitionShowCounter: 'View the counter-hypothesis',
    cognitionHideCounter: 'Hide the counter-hypothesis',
    cognitionCounterMissing: 'No counter-hypothesis yet — confirmation is only possible once there is one.',
    cognitionEvidence: 'Evidence',
    cognitionEvidenceFor: 'for',
    cognitionEvidenceAgainst: 'against',
    cognitionNoEvidence: 'No evidence linked yet.',
    cognitionMacroNote: 'This touches something high-impact. Confirming asks for a deliberate weighing.',
    cognitionImplicationPrompt: 'What does confirming mean here?',
    cognitionImplicationEstablish: 'I settle this statement, as written above.',
    cognitionImplicationCounter: 'I settle the counter-hypothesis.',
    cognitionImplicationSoft: 'I only nudge the confidence.',
    cognitionImplicationPickCorrect: 'First choose what settling means here.',
    cognitionNuance: 'Nuance',
    cognitionNuanceHint: 'Rewrite the statement the way you mean it (optional).',
    cognitionNuancePlaceholder: 'Your wording…',
    cognitionReopen: 'Reconsider',
    cognitionReopenHint: 'You let this go. Take it back under examination? State why.',
    cognitionReopenPlaceholder: 'Why reconsider?',
    cognitionReopenRequired: 'A reason is required to reconsider.',
    cognitionRailOpen: 'Open understanding',
    cognitionRailNew: 'New in understanding',
    cognitionClose: 'Close',
    cognitionResize: 'Resize',
    cognitionAsk: 'Is this right?',
    cognitionYes: 'Yes',
    cognitionNo: 'No',
    cognitionMore: 'More',
    cognitionLess: 'Less',
    cognitionBack: 'Back',
    cognitionMacroSure: 'Are you sure? You are settling this as high-impact.',
    // Logos — episodes (interpretation first, observations on request)
    logos: 'Logos',
    logosTitle: 'Timeline',
    logosHint:
      'Episodes Logos recognised in your activity. What you read is an interpretation — the evidence is underneath, on request.',
    logosEmpty: 'Logos has not recognised an episode yet.',
    logosLoading: 'Loading episodes…',
    logosLoadFailed: 'Logos could not fetch the episodes.',
    logosClose: 'Close',
    logosEpisodeBadge: 'Episode / Interpretation',
    logosBadgeHint: 'Logos inferred this from the observations below — it is not a literal fact.',
    logosSessionPrefix: 'Session',
    logosConfidence: 'confidence',
    logosContext: 'Involved context',
    logosEvidenceToggle: 'View raw evidence',
    logosCaptures: 'captures',
    logosCapture: 'capture',
    logosEvidenceEmpty: 'No raw observations found.',
    logosEvidenceFailed: 'Could not fetch the raw evidence.',
    logosRawObservations: 'Raw observations',
    logosRawNote: 'Recorded directly by capture-rs — not written by Logos.',
    logosOcr: 'OCR',
    logosUia: 'UIA',
    logosAskGaia: 'Ask Gaia',
    logosAskGaiaNotice: 'Gaia opens a conversation with this episode as context.',
    turnNoServer: 'Gaia is not connected to her server yet. You can add one in settings.',
    turnUnreachable: 'Gaia cannot be reached right now.',
    turnUnauthorized: 'Gaia is refusing this connection. Check the token in settings.',
    turnCapture: 'This device could not capture that.',
    turnFallback: 'Something went wrong on this side. Your message is still here.',
    connectionTitle: 'No connection',
    connectionMessage: 'Gaia could not reach her server. Please check your credentials in Settings.',
    connectionOpenSettings: 'Open Settings',
    connectionDismiss: 'Dismiss',
    thoughtProcess: 'Thought process',
    aboutTitle: 'About Gaia',
    aboutCloud: 'Cloud',
    aboutDesktop: 'Desktop',
    aboutBuild: 'build',
    aboutVersion: 'Version',
    aboutUnavailable: 'unavailable',
    aboutConnected: 'connected',
    aboutClose: 'Close',
    // Update panel
    updateTitle: 'Updates',
    updateHint: 'Checking for updates...',
    updateChecking: 'Checking for updates...',
    updateAvailable: 'Update available',
    updateDescription: 'A new version is ready to install.',
    updateVersion: 'Version',
    updateInstall: 'Install Update',
    updateInstalling: 'Installing update...',
    updateDownloaded: 'Update downloaded successfully!',
    updateRestartHint: 'The application needs to restart to complete the update.',
    updateRestart: 'Restart Now',
    updateNotAvailable: 'You have the latest version.',
    updateCheckAgain: 'Check Again',
    updateError: 'Update check failed',
    updateRetry: 'Try Again',
    updateSettings: 'Updates',
    updateCheckForUpdates: 'Check for Updates',
  },
};

const defaultLang = 'nl';

export const L = new Proxy(
  {},
  {
    get(target, prop) {
      const currentLang = localStorage.getItem('gaia.lang') || defaultLang;
      const langData = LANGUAGES[currentLang] || LANGUAGES[defaultLang];
      return langData[prop] || LANGUAGES.en[prop] || prop;
    },
  }
);
